"use client";

import { useState, useCallback, useEffect } from "react";
import { regenerateAISummary } from "@/lib/api";

const COOLDOWN_MS = 3 * 60 * 1000; // 3 minutes

export default function AISummaryCard({ aiSummary, username }) {
  const [summary, setSummary] = useState(aiSummary);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [cooldownEnd, setCooldownEnd] = useState(0);
  const [now, setNow] = useState(Date.now());

  // Sync prop changes
  useEffect(() => {
    setSummary(aiSummary);
  }, [aiSummary]);

  // Tick every second for cooldown countdown
  useEffect(() => {
    if (cooldownEnd <= Date.now()) return;
    const timer = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(timer);
  }, [cooldownEnd]);

  const onCooldown = cooldownEnd > now;
  const cooldownRemaining = onCooldown
    ? Math.ceil((cooldownEnd - now) / 1000)
    : 0;

  const handleRegenerate = useCallback(async () => {
    if (onCooldown || loading) return;
    setLoading(true);
    setError(null);
    try {
      const data = await regenerateAISummary(username);
      setSummary(data.aiSummary);
      setCooldownEnd(Date.now() + COOLDOWN_MS);
    } catch (err) {
      setError("Failed to regenerate summary. Please try again later.");
    } finally {
      setLoading(false);
    }
  }, [username, onCooldown, loading]);

  return (
    <div className="gradient-border card p-6 animate-fade-in-up stagger-6">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <span className="text-lg">✨</span>
          <h3 className="text-lg font-semibold text-[var(--color-text-primary)]">
            AI Summary
          </h3>
          <span className="px-2 py-0.5 rounded-full text-[10px] font-medium bg-[var(--color-accent-indigo)]/15 text-[var(--color-accent-indigo)] border border-[var(--color-accent-indigo)]/25">
            AI-Generated
          </span>
        </div>

        {/* Regenerate button */}
        <button
          onClick={handleRegenerate}
          disabled={onCooldown || loading}
          title={onCooldown ? `Available in ${cooldownRemaining}s` : "Regenerate summary"}
          className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium
                      border transition-all duration-200 cursor-pointer
                      ${onCooldown || loading
                        ? "border-[var(--color-border)] text-[var(--color-text-muted)] cursor-not-allowed opacity-50"
                        : "border-[var(--color-border)] text-[var(--color-text-secondary)] hover:border-[var(--color-accent-indigo)] hover:text-[var(--color-accent-indigo)]"
                      }`}
        >
          <svg
            className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`}
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path strokeLinecap="round" strokeLinejoin="round" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
          </svg>
          {loading ? "Generating..." : onCooldown ? `${cooldownRemaining}s` : "Regenerate"}
        </button>
      </div>

      {/* Summary text */}
      {summary?.text ? (
        <p className="text-sm text-[var(--color-text-secondary)] leading-relaxed">
          {summary.text}
        </p>
      ) : error ? (
        <p className="text-sm text-[var(--color-accent-red)]">{error}</p>
      ) : (
        <p className="text-sm text-[var(--color-text-muted)] italic">
          Summary unavailable. Click regenerate to try again.
        </p>
      )}

      {/* Model attribution */}
      {summary?.model && (
        <p className="mt-3 text-[10px] text-[var(--color-text-muted)]">
          Generated by {summary.model} · {summary.generatedAt
            ? new Date(summary.generatedAt).toLocaleDateString()
            : ""}
        </p>
      )}
    </div>
  );
}
